liocontrol/liocontrol/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='panel/', permanent=False)), 
    url(r'^panel/', include('panel.urls')),
    url(r'^sensors/', include('sensors.urls')),
    url(r'^admin/', admin.site.urls),
    url(
        r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('favicon.ico'),
            permanent=False),
        name="favicon"
    ),
]

handler404 = 'panel.views.handler404'

liocontrol/panel/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'liocontrol'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^config/$', views.config, name='config'),
    url(r'^manual/$', views.manual, name='manual'),
    url(r'^data/$', views.data, name='data'),
    url(r'^camera/$', views.camera, name='camera'),
    url(r'^logs/$', views.logs, name='logs'),
    url(r'^logs/download/$', views.logs_download, name='logs_download'),
    url(r'^close/$', views.manual_close, name='close'),
    url(r'^open/$', views.manual_open, name='open'),
    url(r'^sethigh/$', views.sethigh, name='sethigh'),
    url(r'^setlow/$', views.setlow, name='setlow'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'auth/logged_out.html'}, name='logout'),
    
]

liocontrol/panel/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

class Person(models.Model):
    type = models.CharField(max_length=3)
    desc = models.CharField(max_length=200)
    # TODO: começar a armazenar when como unix time
    when = models.DateTimeField(default=timezone.now)
    #when = models.DateTimeField(auto_now_add=True)
	
class Config(models.Model):
	long = models.DecimalField(max_digits=9,decimal_places=6)
	lati = models.DecimalField(max_digits=8,decimal_places=6)

liocontrol/panel/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.http import JsonResponse

from panel import settings
from .models import Config, Person
from decimal import *
import Adafruit_BBIO.GPIO as GPIO
import time as time_t
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.views import login
from datetime import timedelta
from datetime import time
from datetime import datetime
from time import mktime
from collections import OrderedDict

from astral import Astral
from astral import Location
import urllib
import re
import json
import requests
import csv

l = Location()
l.name = "Sao Carlos"
l.region = "Brasil"
l.latitude = -22.006507
l.longitude = -47.897846
l.timezone = "Brazil/East"
l.elevation = 835

STATE_OPEN =            0b00000000
STATE_CLOSED =          0b11111111
STATE_RAINING =         0b00000001
STATE_NIGHT =           0b00000010
STATE_MANUAL_OPEN =     0b10000000
STATE_MANUAL_CLOSED =   0b10000011

MODE_AUTO           = 0b00000000
MODE_MANUAL_OPEN    = 0b10000000
MODE_MANUAL_CLOSED  = 0b10000001

def index(request):
    if request.user.is_authenticated():
        # Get sunrise and sunset times
        sunrise = l.sunrise().strftime("%H:%M:%S")
        sunset = l.sunset().strftime("%H:%M:%S")
        # Load sensors data
        iuv = 0
        data_hora = 'default'
        try:
            #r = requests.get("http://192.168.1.111:8008/json_data", timeout=5)
            
            r = requests.get('http://www.sel.eesc.usp.br/liosensors/json_data.php', timeout=5)
            data = r.json()
            #iuv = str(data['sensors'][0]['lastUV'])
            iuv = str(data['lastUV'])
            iuv = float(iuv)
            iuv = round(iuv)
            iuv = int(iuv)
            iuv = str(iuv)
            #data_hora = data['sensors'][0]['time']
            data_hora = data['time']
        except Exception as ex:
            iuv = 0
            data_hora = 'Falha ao consultar dados do IUV'
            print 'Exception'
        #htmlfile=urllib.urlopen("http://192.168.1.111:8008/json_data")
        #htmltext=htmlfile.read()
        #data = json.loads(htmltext)
        # Get UVI and sensors timestamp
        
        # Get mode and expected state
        fMode = open("/home/lio/controle-remoto/control/mode", "r")
        fExpectedState = open("/home/lio/controle-remoto/control/expectedState", "rb")

        mode = ord(fMode.read(1))
        expectedState = int(ord(fExpectedState.read(1)))
        
        fMode.close()
        fExpectedState.close()
        
        manual = False
        night = False
        rain = False
        if(mode != MODE_AUTO):
            manual = True
        elif(expectedState & STATE_NIGHT != STATE_OPEN):
            night = True
        elif(expectedState & STATE_RAINING != STATE_OPEN):
            rain = True
            
        state = "Pânico"
        stateColor = "#FF0000"
        fActualState = open("/home/lio/controle-remoto/control/actualState", "rb")
        actualState = int(ord(fActualState.read(1)))
        fActualState.close()
        if(actualState == STATE_OPEN):
            state = "Aberto"
            stateColor = "#00FF00"
        elif(actualState == STATE_CLOSED):
            state = "Fechado"
            stateColor = "#00FF00"
        # Get system time
        now = (datetime.now()+timedelta(minutes=2)).strftime("%d-%m-%Y %H:%M:%S");

        return render(request, "panel/index.html", {'now': now, 'iuv_data_hora': data_hora, 'state': state, 'state_color': stateColor, 'rain':rain, 'night':night, 'iuv': iuv, 'sunrise': sunrise, 'sunset': sunset, 'manual': manual})
    else:
        return HttpResponseRedirect(reverse('liocontrol:login'))


def config(request):
    if request.user.is_authenticated():
        if request.method == "POST":
        # create a form instance and populate it with data from the request:
            longitude = Decimal(request.POST.get("longitude")).quantize(Decimal('.000001'), rounding=ROUND_DOWN)
            latitude = Decimal(request.POST.get("latitude")).quantize(Decimal('.000001'), rounding=ROUND_DOWN)
            print longitude
            if (longitude > 180.0 or longitude < -180.0 or latitude > 90.0 or latitude < -90.0):
                return HttpResponse("Error")
            else:
                config = Config.objects.get(pk=1)
                config.long = longitude
                config.lati = latitude
                config.save()
                return render(request, "panel/config.html", {'config': config})
                
        
        try:
            config = Config.objects.get(pk=1)
        except Config.DoesNotExist:
            return HttpResponse("Config does not exist")
        return render(request, "panel/config.html", {'config': config})
    else:
        return HttpResponseRedirect(reverse('liocontrol:login'))

def manual(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            mode = request.POST.get("mode")            
            try:
                fMode = open("/home/lio/controle-remoto/control/mode", "r+")
                actualMode = ord(fMode.read(1))
                fMode.seek(0)
                if(mode == 'auto' and actualMode != MODE_AUTO):
                    fMode.write(chr(MODE_AUTO))
                    p = Person(type="ma", desc="Modo alterado para automático.")
                    p.save()
                elif(mode == 'manual_open' and actualMode != MODE_MANUAL_OPEN):
                    fMode.write(chr(MODE_MANUAL_OPEN))
                    p = Person(type="mmo", desc="Modo alterado para manual aberto.")
                    p.save()
                elif(mode == 'manual_closed' and actualMode != MODE_MANUAL_CLOSED):
                    fMode.write(chr(MODE_MANUAL_CLOSED))
                    p = Person(type="mmc", desc="Modo alterado para manual fechado.")
                    p.save()
                else:
                    p = Person(type="wm", desc="WARNING: O modo solicitado não é válido.")
                    p.save()
                    fMode.close()
                    return HttpResponseBadRequest()          
                
                fMode.close()
                return HttpResponse()
            except IOError:
                p = Person(type="em", desc="ERROR (IOError): Falha ao alterar o modo.")
                p.save()
                
                return HttpResponseBadRequest("ERROR (IOError): Falha ao alterar o modo.")
        else:
            try:
                fMode = open("/home/lio/controle-remoto/control/mode", "r")
                mode = ord(fMode.read(1))
                fMode.close()
                
                manual = False
                manual_closed = False
                print mode
                print MODE_MANUAL_OPEN
                if(mode == MODE_MANUAL_OPEN):
                    manual = True
                elif(mode == MODE_MANUAL_CLOSED):
                    manual = True
                    manual_closed = True
                
                return render(request, "panel/manual.html", {'manual': manual, 'manual_closed': manual_closed})
            except IOError:
                p = Person(type="em", desc="ERROR (IOError): Falha ao consultar o modo.")
                p.save()
                
                return HttpResponseBadRequest("ERROR (IOError): Falha ao consultar o modo.")
    else:
        return HttpResponseRedirect(reverse('liocontrol:login'))
    
def data(request):
    # Uptime
    with open('/proc/uptime', 'r') as f:
            uptime_seconds = float(f.readline().split()[0])
            t = timedelta(seconds = uptime_seconds)
            hours = t.seconds//3600
            minutes = (t.seconds//60)%60
            seconds = t.seconds%60
            uptime_string = str(t.days) + ' dia(s), ' + str(hours).zfill(2) + ':' + str(minutes).zfill(2) + ':' + str(seconds).zfill(2)
       
    return HttpResponseRedirect(reverse('liocontrol:login'))

def camera(request):
    return render(request, "panel/camera.html")

def logs(request):
    if request.user.is_authenticated():
        time = int(request.GET.get('time', '1'))
        type = int(request.GET.get('type', '1'))
        type_chr = ''
        if (type == 2):
            type_chr = 'e'
        if (type == 3):
            type_chr = 'a'
        if (type == 4):
            type_chr = 'f'
        objects_ftime = Person.objects.filter(when__lte=datetime.today(), when__gt=datetime.today()-timedelta(hours=24*time))
        objects = objects_ftime.filter(type__startswith=type_chr)
        return render(request, "panel/log.html", {'object_list': objects, 'current_path': request.get_full_path(), 'type': type, 'time': time})
    else:
        return HttpResponseRedirect(reverse('liocontrol:login'))

def logs_download(request):
    if request.user.is_authenticated():
        time = int(request.GET.get('time', '1'))
        type = int(request.GET.get('type', '1'))
        type_chr = ''
        if (type == 2):
            type_chr = 'e'
        if (type == 3):
            type_chr = 'a'
        if (type == 4):
            type_chr = 'f'
        objects_ftime = Person.objects.filter(when__lte=datetime.today(), when__gt=datetime.today()-timedelta(hours=24*time))
        objects = objects_ftime.filter(type__startswith=type_chr)
        
        # Create the HttpResponse object with the appropriate CSV header.
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="logs.csv"'
        
        writer = csv.writer(response)
        writer.writerow(['Data e Hora', 'Tipo', u'Descrição'.encode('utf-8')])
        for o in objects:
            # TODO: adicionar tempo UNIX no CSV [int(mktime(o.when.timetuple())), mas antes precisa corrigir no models.py

liocontrol/panel/templates/panel/camera.html
<iframe style="height: 100%; overflow: hidden;" scrolling="no" frameborder="0" src="http://admin:123456@143.107.235.2:8010/mjpeg/stream.cgi?chn=0"></iframe> 
<!--
<iframe src="http://ipcamlive.com/player/player.php?alias=59412bd3cd018" width="800px" height="600px"/>
-->

liocontrol/panel/templates/panel/config.html
{% extends 'base.html' %}

{% load static %}

{% block title %}LIO{% endblock %}

{% block navLinks %}
    <li><a href="{% url 'liocontrol:index' %}">Home</a></li>
    <li><a href="{% url 'liocontrol:config' %}">Configuração</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
{% endblock %}
{% block navLinksMobile %}
    <li><a href="{% url 'liocontrol:index' %}">Home</a></li>
    <li><a href="{% url 'liocontrol:config' %}">Configuração</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
{% endblock %}

{% block content %}
<div class="row">

<div class="col s6 z-depth-4 card-panel">
    <div class="card">
        <div class="card-content">

            <span class="card-title">Configurações</span>
            <div class="row">
                <form action="" method="post" class="col s12">
                {% csrf_token %}
                    <div class="input-field col s6">
                        <input id="longitude" name="longitude" type="text" class="validate" value="{{ config.long }}">
                        <label for="longitude">Longitude</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="latitude" name="latitude" type="text" class="validate" value="{{ config.lati }}">
                        <label for="latitude">Latitude</label>
                    </div>
                    <button class="btn waves-effect waves-light col s12" type="submit">Salvar</button>
                </form>
            </div>
        </div>
        <div class="card-action">
            <a href="#">Salvar</a>
            <a href="#">Limpar</a>
        </div>
    </div>
</div>

{% endblock %}

liocontrol/panel/templates/panel/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}LIO{% endblock %}

{% block navLinks %}
    <li><a href="{% url 'liocontrol:index' %}">Início</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
    <li><a href="{% url 'liocontrol:manual' %}">Manual</a></li>
    <li><a href="{% url 'liocontrol:data' %}">Dados Técnicos</a></li>
    <li><a href="{% url 'liocontrol:logout' %}">Sair</a></li>
{% endblock %}
{% block navLinksMobile %}
    <li><a href="{% url 'liocontrol:index' %}">Início</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
    <li><a href="{% url 'liocontrol:manual' %}">Manual</a></li>
    <li><a href="{% url 'liocontrol:data' %}">Dados Técnicos</a></li>
    <li><a href="{% url 'liocontrol:logout' %}">Sair</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col s1 z-depth-1 card-panel">
        <img style="margin-top:25%;" src="{% static '/panel/images/logos/usp-logo-png-transparente.png' %}" alt="Pôr do sol" width="100%">
        <img style="margin-top:25%;" src="{% static '/panel/images/logos/logo_eesc_vertical.jpg' %}" alt="Pôr do sol" width="100%">
        <img style="margin-top:25%;" src="{% static '/panel/images/logos/logoLIO-correto-AZUL.bmp' %}" alt="Pôr do sol" width="100%">
        <img style="margin-top:25%;" src="{% static '/panel/images/logos/cnpq.png' %}" alt="Pôr do sol" width="100%">
        <img style="margin-top:25%;" src="{% static '/panel/images/logos/FAPESP.jpg' %}" alt="Pôr do sol" width="100%">
    </div>

    <div class="col s8 z-depth-1 card-panel">
        <div class="card">
            <div class="card-content">
                <div style="height:48px">
                    <span style="display:inline-block;" class="card-title">Sistema de Exposição Solar ({{ now }})</span> 
                    <!--<span style="color: {{ state_color }}; font-size:calc(12px + 1vw); margin-left:10%;"> {{ state }} </span>
                   
                    <span style="color: {{ state_color }}; font-size:calc(12px + 1vw); margin-left:10%;"> {{ state }} </span>
                     -->
                    {% if manual %}
                    <img style="vertical-align:middle; margin-left:10%;" src="{% static '/panel/images/manual.png' %}" alt="Controle manual" height="100%">
                    {% elif rain %}
                    <img style="vertical-align:middle; margin-left:10%;" src="{% static '/panel/images/rain.png' %}" alt="Pôr do sol" height="100%">
                    {% elif night %}
                    <img style="vertical-align:middle; margin-left:10%;" src="{% static '/panel/images/night.png' %}" alt="Noite" height="100%">
                    {% endif %}
                    
                </div>
                <img class="shrinkToFit" style="width:100%;" src="http://admin:123456@143.107.235.2:8010/mjpeg/stream.cgi?chn=0" alt="http://admin:123456@143.107.235.2:8010/mjpeg/stream.cgi?chn=0">
            </div>
        </div>
    </div>

    <div class="col s3 z-depth-1 card-panel">
        <div class="card">
            <div class="card-content" style="height:100%; width:100%; overflow: hidden;">
                <div style="float: left; width:75%;">
                    <div>
                        <img style="vertical-align:middle" src="{% static '/panel/images/sunrise.png' %}" alt="Nascer do sol" width="25%" height="25%">
                        <span style="vertical-align:middle; margin-left:5%; font-size:1.8vw">{{ sunrise }}</span>
                    </div>
                    <div style="margin-top:5%">
                        <img style="vertical-align:middle" src="{% static '/panel/images/sunset.png' %}" alt="Pôr do sol" width="25%" height="25%">
                        <span style="vertical-align:middle; margin-left:5%; font-size:1.8vw">{{ sunset }}</span>
                    </div>
                </div>
                <div style="float: left; width:25%; height:100%;">
                        {% static "" as baseUrl %}
                        <img style="width:100%; height:100%" src="{{ baseUrl }}panel/images/uv/UVI_{{ iuv }}.png" alt="Índice ultra violeta">
               </div>
               <div style="float: right;">
                    {{ iuv_data_hora }}
                    </div>
                
            </div>
        </div>
        <div class="card">
            <div class="card-content" style="height:100%; width:100%; overflow: hidden;">
                <span class="card-title">Rotação das lentes </span>               
            </div>
            <!-- TODO: mudar margens -->
            <div style="vertical-align:middle; margin-left:5%; margin-top:-10%;">
                27/01/17 a 13/11/17 ==> NORTE
                <b>14/11/17 em diante ==> SUL</b>
            </div>
        </div>
        <div class="card">
            <div class="card-content">
                <span class="card-title">Resumo (24 horas)</span>
            </div>
            <canvas id="pie-chart-sample" width="472" height="236" style="width: 472px; height: 236px;"></canvas>
            <table class="table remove-background">
                <tbody>
                <tr>
                    <td style="padding: 5px 5px;" class="text-left size-sm">
                        <div style="background-color:#f7f000;min-width: 10px;height: 10px;"></div>Exposto</td>
                </tr><tr>
                    <td style="padding: 5px 5px;" class="text-left size-sm">
                        <div style="background-color:#000000;min-width: 10px;height: 10px;"></div>Noite</td>
                </tr><tr>
                    <td style="padding: 5px 5px;" class="text-left size-sm">
                        <div style="background-color:#46BFB0;min-width: 10px;height: 10px;"></div>Chuva</td>
                </tr></tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static '/panel/js/chart.min.js' %}"></script>
<script type="text/javascript" src="{% static '/panel/js/chart.js' %}"></script>


{% endblock %}

liocontrol/panel/templates/panel/log.html
{% extends 'base.html' %}

{% load static %}

{% block title %}LIO{% endblock %}

{% block navLinks %}
    <li><a href="{% url 'liocontrol:index' %}">Início</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
    <li><a href="{% url 'liocontrol:manual' %}">Manual</a></li>
    <li><a href="{% url 'liocontrol:data' %}">Dados Técnicos</a></li>
    <li><a href="{% url 'liocontrol:logout' %}">Sair</a></li>
{% endblock %}
{% block navLinksMobile %}
    <li><a href="{% url 'liocontrol:index' %}">Início</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
    <li><a href="{% url 'liocontrol:manual' %}">Manual</a></li>
    <li><a href="{% url 'liocontrol:data' %}">Dados Técnicos</a></li>
    <li><a href="{% url 'liocontrol:logout' %}">Sair</a></li>
{% endblock %}

{% block content %}
<div class="row">

<div class="col s8 z-depth-1 card-panel">
    <div class="card">
        <div class="card-content">
            <table class="highlight">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Descrição</th>
                        <th>Quando</th>
                    </tr>
                </thead>
                <tbody>
                    {% for event in object_list %}
                    <tr>
                        <td>{{ event.type}}</td>
                        <td>{{ event.desc }}</td>
                        <td>{{ event.when|date:'d/m/Y H:i:s'  }}</td>
                    </tr>
                    {% empty %}
                    <li>Nenhum registro encontrado.</li>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="col s4 z-depth-1 card-panel">
    <div class="card">
        <div class="card-content">
            <span class="card-title">Filtro e Download</span>
		
            <div class="row">
           <div class="input-field col s6">
           
            <label>Período</label><br><br>
              <select id="tempo_filtro" class="browser-default">
                <option value="1" {% if time == 1 %}selected{% endif %}>Últimas 24 horas</option>
                <option value="3" {% if time == 3 %}selected{% endif %}>Últimos 3 dias</option>
                <option value="7" {% if time == 7 %}selected{% endif %}>Últimos 7 dias</option>
                <option value="30" {% if time == 30 %}selected{% endif %}>Últimos 30 dias</option>
              </select>
          </div>
          
           <div class="input-field col s6">
           
            <label>Tipo</label><br>
            <p>
              <input name="tipo_filtro" type="radio" id="tipo_filtro1" value="1" {% if type == 1 %}checked{% endif %} />
              <label for="tipo_filtro1">Todos</label>
            </p>
            <p>
              <input name="tipo_filtro" type="radio" id="tipo_filtro2" value="2" {% if type == 2 %}checked{% endif %} />
              <label for="tipo_filtro2">Eventos</label>
            </p>
            <p>
              <input name="tipo_filtro" type="radio" id="tipo_filtro3" value="3" {% if type == 3 %}checked{% endif %} />
              <label for="tipo_filtro3">Alertas</label>
            </p>
            <p>
              <input name="tipo_filtro" type="radio" id="tipo_filtro4" value="4" {% if type == 4 %}checked{% endif %} />
              <label for="tipo_filtro4">Erros</label>
            </p>
            </div>
            </div>
             <button type="button" onclick="filter()">Filtrar</button>
             <button type="button" onclick="download()">Download</button>
             <script>
             
            
            function filter() {
            
            // TODO: indicar que está filtrando (loading...)
                // Declare variables
                var tempo_filtro, tempo, tipo_filtro, tipo, table, tr, td, i;
                tempo_filtro = document.getElementById("tempo_filtro");
                tempo = tempo_filtro.value;
                tipo_filtro = document.getElementsByName('tipo_filtro');
                for (var i = 0, length = tipo_filtro.length; i < length; i++) {
                    if (tipo_filtro[i].checked) {
                        tipo = tipo_filtro[i].value;
                        break;
                    }
                }
                
                // TODO: automatically get my URL
                var myURL = 'http://143.107.235.2:8000/panel/logs?';
                var params = { 'type':tipo, 'time':tempo };
                var new_url = myURL + $.param(params);
                document.location = new_url;
            }
            
            
            function download() {
            
            // TODO: indicar que está filtrando (loading...)
                // Declare variables
                var tempo_filtro, tempo, tipo_filtro, tipo, table, tr, td, i;
                tempo_filtro = document.getElementById("tempo_filtro");
                tempo = tempo_filtro.value;
                tipo_filtro = document.getElementsByName('tipo_filtro');
                for (var i = 0, length = tipo_filtro.length; i < length; i++) {
                    if (tipo_filtro[i].checked) {
                        tipo = tipo_filtro[i].value;
                        break;
                    }
                }
                
                // TODO: automatically get my URL
                var myURL = 'http://143.107.235.2:8000/panel/logs/download?';
                var params = { 'type':tipo, 'time':tempo };
                var new_url = myURL + $.param(params);
                document.location = new_url;
            }
            
            </script>
        </div>
    </div>
</div>
</div>

<script type="text/javascript" src="{% static '/panel/js/jquery-3.2.1.js' %}"></script>

{% endblock %}

liocontrol/panel/templates/panel/manual.html
{% extends 'base.html' %}

{% load static %}

{% block title %}LIO{% endblock %}

{% block navLinks %}
    <li><a href="{% url 'liocontrol:index' %}">Início</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
    <li><a href="{% url 'liocontrol:manual' %}">Manual</a></li>
    <li><a href="{% url 'liocontrol:data' %}">Dados Técnicos</a></li>
    <li><a href="{% url 'liocontrol:logout' %}">Sair</a></li>
{% endblock %}
{% block navLinksMobile %}
    <li><a href="{% url 'liocontrol:index' %}">Início</a></li>
    <li><a href="{% url 'liocontrol:logs' %}">Registros</a></li>
    <li><a href="{% url 'liocontrol:manual' %}">Manual</a></li>
    <li><a href="{% url 'liocontrol:data' %}">Dados Técnicos</a></li>
    <li><a href="{% url 'liocontrol:logout' %}">Sair</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col s2"></div>
    <div class="col s8 z-depth-1 card-panel">
            <div class="card">
                <div class="card-content">
                    <span style="display:inline-block;" class="card-title">Controle manual</span> 
                    
                    <div class="row">
                        <div class="col s6">
                            <p><b>Estado atual:</b> controle manual
                            {% if manual %}
                            <font color="red">ativo</font>!
                            {% else %}
                            <font color="green">inativo</font>!
                            {% endif %}
                            </p>
                            
                        </div>
                                            
                        <div class="input-field col s6">
                            <label>Modo</label><br>
                            <p>
                              <input name="mode" type="radio" id="mode_auto" value="1"
                              {% if not manual %}checked{% endif %}
                              />
                              <label for="mode_auto">Automático</label>
                            </p>
                            <p>
                              <input name="mode" type="radio" id="mode_manual_open" value="2"
                              {% if manual %}{% if not manual_closed %}checked{% endif %}{% endif %}
                              />
                              <label for="mode_manual_open">Manual - Aberto</label>
                            </p>
                            <p>
                              <input name="mode" type="radio" id="mode_manual_closed" value="3"
                              {% if manual_closed %}checked{% endif %}
                              />
                              <label for="mode_manual_closed">Manual - Fechado</label>
                            </p>
                            <button type="button" style="margin-top:20px" onclick="change()">Alterar</button>
                        
                        </div>
                        
                        <div class="col s11 right-align">
                        </div>
                            
                    </div>
                            
                            <script>
                                function change() {
                                    if (document.getElementById('mode_auto').checked) {
                                        mode = 'auto';
                                    } else if (document.getElementById('mode_manual_open').checked) {
                                        mode = 'manual_open';
                                    } else if (document.getElementById('mode_manual_closed').checked) {
                                        mode = 'manual_closed';
                                    }
                                    $.post("/panel/manual/", {csrfmiddlewaretoken: '{{ csrf_token }}', mode: mode}, function() {
                                        location.reload();
                                        });
                                    }
                            </script>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}